name: Deploy Node API

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint and Test
        run: |
          npm run lint
          npm test

      - name: Log test result
        run: |
          node updateVersionJson.js "$NEW_VERSION" "test" "Tests unitaires réussis"

      - name: Log lint result
        run: |
          node updateVersionJson.js "$NEW_VERSION" "lint" "Lint OK"


      - name: Increment version
        id: version
        run: |
          # Incrémente la version patch et récupère la nouvelle
          NEW_VERSION=$(npm version patch -m "chore: bump version to %s [ci skip]")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update changelog
        run: |
          echo "Nouvelle version : $NEW_VERSION"
          node updateChangelog.js "$NEW_VERSION"

      - name: Build (si tu build un frontend ou TS)
        run: echo "Pas de build pour une API simple"

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV

      # Auto deploy
      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
