name: Fix Branch CI

on:
  push:
    branches:
      - fix/**  
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Comment on linked issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Les tests ont été exécutés sur la branche de correctif **${{ github.ref }}**
            et tous les tests sont passés.
          token: ${{ secrets.GITHUB_TOKEN }}
